[package]
name = "stakenet-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anchor-lang = { workspace = true }
anyhow = "1.0.98"
borsh = "0.10.0"
bytemuck = { features = ["derive", "min_const_generics"], version = "1.13.1" }
thiserror = { workspace = true }
serde = { workspace = true }
clap = { version = "4", features = ["derive", "env"] }
futures = "0.3.31"
num-traits = { workspace = true }
shlex = "1.3.0"
solana-client = { workspace = true }
solana-sdk = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
sqlx = { workspace = true, features = ["postgres", "runtime-tokio-native-tls", "chrono", "bigdecimal" ] }
dotenvy = { workspace = true }
envy = "0.4.2"
stakenet-simulator-db = { workspace = true }
validator-history = { workspace = true }
jito-steward = { workspace = true }
type-layout = "0.2"